services:
  postgres:
    image: postgres:15
    restart: always
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      timeout: 3s
      retries: 5
      # On runtime
      interval: 600s
      # On start
      start_period: 20s
      start_interval: 2s

  app:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - ./app:/app/app
      - ./logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "${APP_PORT}:8000"
    command: >
      sh -c "
      uv run alembic upgrade head
      &&
      uv run uvicorn app.__main__:app
      --host 0.0.0.0
      --port 8000
      --log-level info
      --proxy-headers
      --forwarded-allow-ips=*
      "
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
    restart: always

volumes:
  postgres_data:
